### ISSUE TITLE
Align left not working

### ISSUE THREAD

**Issue by parisni** [farbelous/bootstrap-colorpicker#117]
Hello,

I have a color picker element on the right of my screen. As the palette goes on the right, it desapears from screen. I would like to invert it (on the left of the element).
I guess, the option align should do that ? 

my code :
<code>
${"div"}.colorpicker({align:'left'}).on(...)
</code>

The palette still goes on right 

Thanks for all

**Comment by dericeira** [comment]
I'm having this same issue :-1:

**Comment by mjolnic** [comment]
This will be fixed in the next major release, introducing placements like in the [Popover Picker](https://mjolnic.com/bootstrap-popover-picker/)  plugin. There you will have more positioning options.
