### ISSUE TITLE
Interfering with Bootstrap Modal

### ISSUE THREAD

**Issue by Jak893** [farbelous/bootstrap-colorpicker#136]
I've encountered quite a peculiar issue, when loading a Bootstrap modal, the colour picker seems to be rendered above the content of the modal. After some digging, I discovered that a z-index of 2500 has been set within the pickers CSS.

Is there a reason for specifying such a high z-index? Will lowering it to something a bit more reasonable, say 1 or 2 cause any issues later on. From what I can see it is simply a rendered div and input control so such a high z-index would be unnecessary surely?

**Comment by itsjavi** [comment]
I think this has been fixed. closing issue
