### ISSUE TITLE
Colorpicker popover most doesn't close on IOS when you click elsewhere

### ISSUE THREAD

**Issue by asaadmahmood** [farbelous/bootstrap-colorpicker#169]
I even tried https://mjolnic.com/bootstrap-colorpicker/ on an IOS simulator, and that doesn't work either.

**Comment by mjolnic** [comment]
which iOS and Safari version are the ones you tried?

**Comment by asaadmahmoodspin** [comment]
Iphone 6s verision 9.3.3.

**Comment by itsjavi** [comment]
@asaadmahmood please can you confirm that it is fixed with v2.4.0 (latest) ? thanks
