### ISSUE TITLE
Add support for Android color format

### ISSUE THREAD

**Issue by JakubKahovec** [farbelous/bootstrap-colorpicker#177]
Hi,
would it be possible to add support Android color format #AARRGGBB (https://developer.android.com/guide/topics/resources/more-resources.html#Color)
Thanks

**Comment by itsjaviaguilar** [comment]
This is not a priority right now, but it can be considered as a feature for the future.

**Comment by ghelyar** [comment]
For what it's worth, the CSS 4 draft has an 8 digit hex color format and at the moment it looks like it's going to be #RRGGBBAA (also 4 digit #RGBA), which conflicts with the argb format suggested here. It also makes sense to use rgba considering that's what is already in use by css.

**Comment by itsjavi** [comment]
`#RRGGBBAA` support has now been added to `master` and will be available in next release `v3.0.0`
