### ISSUE TITLE
Color picker displays in background in bootstrap modal and when click on it, modal and colorpicker disappear

### ISSUE THREAD

**Issue by JohnMerlino2** [farbelous/bootstrap-colorpicker#194]
The Color picker displays in background in bootstrap modal and when click on it, modal and colorpicker disappear. This is what it looks like: https://s30.postimg.org/xbe7bzqn5/colorpicker_issue.jpg

**Comment by itsjavi** [comment]
Sorry, I cannot help you without a working example :
https://github.com/itsjavi/bootstrap-colorpicker/blob/master/CONTRIBUTING.md

**Comment by Tanex** [comment]
Just ran into the same issue. 
It's caused by the bootstrap class .dropdown-menu overriding the z-index specified in boostrap-colorpicker.css .colorpicker causing it to have a z-index of 1000 instead of 2500 so it ends up behind the modal. I don't have the time at the moment to create a fiddle but hopefully this helps a bit

**Comment by sguedon** [comment]
Same kind of issue in a modal. colopicker appears at the end of the modal when using container: true or end of body without

![image](https://user-images.githubusercontent.com/29616237/27411793-711fe590-56f0-11e7-96e8-9313f718a3a4.png)

Once clicked:
![image](https://user-images.githubusercontent.com/29616237/27411840-b7708ab8-56f0-11e7-87bf-4186f4417249.png)

html code
<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
			<h4 class="modal-title" id="AboutModal-title"></h4>
			</div>
		<div class="modal-body" id="AboutModal-body" style="color: rgb(0, 0, 0);"><form id="AddItem2Graph" name="AddItem2Graph" method="post" role="form" onsubmit="AddThisItemToGraph(this,&quot;&quot;);"><label>Object type to add to graph: </label><select name="ItemType" id="ItemType" class="form-control" onchange="ChangesubSelections('Text|Image|WebURL', this.value);"> 
<option value="Text">Text type object</option>
<option value="Image">Image type object</option>
<option value="WebURL">Web URL type object</option>
</select><br><div id="Text"><label>Text style: </label><select name="Item_Text_Style" id="Item_Text_Style" class="form-control">
<option value="h1" selected="">large</option>
<option value="h2">medium</option>
<option value="p">small</option>
</select><label>Text Color: </label><div class="input-group colorselection colorpicker-element" id="ModalColorPicker" style="top: 0px;">
<input type="text" id="Item_Text_Color" name="Item_Text_Color" value="#000000" class="form-control">
<span class="input-group-addon"><i style="background-color: rgb(0, 0, 0);"></i></span>
<div class="colorpicker dropdown-menu colorpicker-visible" style="z-index: 3000; top: 357px; left: 944.167px;"><div class="colorpicker-saturation" style="background-color: rgb(255, 0, 0);"><i style="top: 100px; left: 0px;"><b></b></i></div><div class="colorpicker-hue"><i style="top: 100px;"></i></div><div class="colorpicker-alpha" style="background-color: rgb(0, 0, 0);"><i style="top: 0px;"></i></div><div class="colorpicker-color" style="background-color: rgb(0, 0, 0);"><div style="background-color: rgb(0, 0, 0);"></div></div></div></div>
<label>Text to display: </label>   <input required="" type="text" autocomplete="off" class="form-control" name="Item_Text_Value" id="Item_Text_Value" value="">
</div><div id="Image"><label>Image filename: </label>   <input $inputattribute="" required="" type="text" autocomplete="off" class="form-control" name="Item_Image_Value" id="Item_Image_Value" value="">
</div>                         <div class="modal-footer">
                                 <div class="pull-left">                                 <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
                                 </div>                                 <div class="pull-right">                                 <button type="submit" class="btn btn-primary" id="submit_AddItem2Graph">Add</button>
                                 </div>                         </div>
</form></div>
         </div>
  </div>
