### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by miherlosev** [farbelous/bootstrap-colorpicker#206]
I propose to add e2e tests for basic scenarios: 'simple input field', 'component mode', 'horizontal mode' and etc. I can write them using [TestCafe](http://github.com/devexpress/testcafe).
What do you think about it?

**Comment by itsjavi** [comment]
I am not familiar with that framework, but I am open to have some tests if you are willing to maintain them ;)

Anyway I would prefer to have tests that can be automatically run without manual user interaction, so we can put them on travis CI and will be executed on each commit.

Phantom and Jasmine seem better choices for that. Unfortunately I have no time for that :(

**Comment by itsjavi** [comment]
This will be done soon with `jsdom` and `AVA`.
