### ISSUE TITLE
Fallback color option not used when invalid value is entered

### ISSUE THREAD

**Issue by mdg357** [farbelous/bootstrap-colorpicker#207]
I'm setting the `fallbackColor` and `fallbackFormat` in order to show a default value of "#ffffff". However, if delete all of the text in the input field, then type something invalid (ex. "!"), I would expect the value to default to what I set as the `fallbackColor`. 

JSFiddle example [here](https://jsfiddle.net/e8sza3rp/1/)

Looking at the code, I believe that the issue lives somewhere around line 37 or so:

```
/**
   * Color manipulation helper class
   *
   * @param {Object|String} [val]
   * @param {Object} [predefinedColors]
   * @param {String|null} [fallbackColor]
   * @param {String|null} [fallbackFormat]
   * @param {Boolean} [hexNumberSignPrefix]
   * @constructor
   */
  var Color = function(
    val, predefinedColors, fallbackColor, fallbackFormat, hexNumberSignPrefix) {
    this.fallbackValue = fallbackColor ?
      (
        fallbackColor && (typeof fallbackColor.h !== 'undefined') ?
        fallbackColor :
        this.value = {
          h: 0,
          s: 0,
          b: 0,
          a: 1
        }
      ) :
      null;
```

Specifically, the check being done to set `this.fallback`

`(typeof fallbackColor.h !== 'undefined')`

Since `fallbackColor` is of type `string` it does not have a `.h` property, so that check will always fail, defaulting us to the color black.

**Comment by itsjavi** [comment]
you are right, thanks for  the hint and for providing a fiddle example ❤️

**Comment by itsjavi** [comment]
fixed
