### ISSUE TITLE
Feature request: hide/remove the alpha bar

### ISSUE THREAD

**Issue by awguo** [farbelous/bootstrap-colorpicker#208]
This may be the best color picker I've tried. But only one thing: I want to hide the alpha bar for some cases. Is it possible to add something like this in the options?

`$('.sample-selector').colorpicker({ showAlphaBar: false });`

Thanks,

**Comment by h2ooooooo** [comment]
You can make the bar disappear by using a format like `hex`:

    $('input').colorpicker({ format: 'hex' });

**Comment by itsjavi** [comment]
new option `useAlpha` has now been added in `master`. It not only hides the alpha bar, but also disables the possibility to set an alpha channel in the input manually
