### ISSUE TITLE
Colors are not displayed if Jquery is added above the angularJS

### ISSUE THREAD

**Issue by amanguptaDeveloper** [farbelous/bootstrap-colorpicker#209]
Hi, I have found a strange issue where if i add Jquery above the angular js, bootstrap color picker stops displaying the colors.
In my index.html
<script src="assets/libs/jquery-1.12.4.min.js"></script>
    <script src="assets/libs/angular.min.js"></script>

I am doing this so as to use custom scroller where they require Jquery to be initialized before angular. Can you please help ?

**Comment by itsjavi** [comment]
Please follow the issue guidelines: https://github.com/farbelous/bootstrap-colorpicker/blob/master/CONTRIBUTING.md#steps-to-submit-an-issue
