### ISSUE TITLE
Color Picker position with centering CSS: margin-left and -right auto

### ISSUE THREAD

**Issue by maverick42** [farbelous/bootstrap-colorpicker#220]
Hi

Many site have centering css with margin-left an -right : auto. Exemple :
.container {
  margin-right: auto;
  margin-left: auto;
  padding-left: 13px;
  padding-right: 13px;
}

My theme, smartadmin (http://wrapbootstrap.com/preview/WB0573SK0), allow this feature.

![image](https://user-images.githubusercontent.com/2311642/28199795-a9b606d0-6868-11e7-8c12-a1386f2e6836.png)

A demo a bootstrap colorpicker is on forms -> forms plugins page. With css center the color picker is moved to the right

![image](https://user-images.githubusercontent.com/2311642/28199836-fce612fa-6868-11e7-875d-1774dbb831a4.png)

I made this change to reflect this shiftbut I do not know if this is the best solution. Can you validate it?

![image](https://user-images.githubusercontent.com/2311642/28200013-cf9565ac-6869-11e7-971c-fab858bb5db9.png)

Best
Fréderik

**Comment by itsjavi** [comment]
Hello @maverick42 can you provide a demo in JsFiddle?
