### ISSUE TITLE
ColorPicker only on double click?

### ISSUE THREAD

**Issue by jetic83** [farbelous/bootstrap-colorpicker#221]
Hi, how would it be best possible to open the colorpicker only on double click on the color field?

Now, it opens on single click on an element with a colorpicker. But I want the colorpicker to show up only on double click on an element with a picker. Is there an option for that?

Thanks!

**Comment by jetic83** [comment]
The reason for this design is that I have 5 small colored divs in my webapp, each with a color picker. 

With a single click on such a field, I want to select the field and the color to e.g. paint with that in my webapp. 

With a double click on such a fiield, I want to open the picker to change the color of this field.

**Comment by jetic83** [comment]
I solved this issue by using .colorpicker('disable') in the 'hidePicker' event and .colorpicker('enable') on a double click event again.

However, disable and enable only work if there is an input element appended to the colored divs. So, I first had to append input elements to the inputs which have style=display:none.

It would be better, if colorpickers could be disabled and enabled regardless of an input element.

**Comment by itsjavi** [comment]
You can build your own components with the API of the colorpicker, and assign an event on double click.
The plugin is designed to work with a single click and should not become more complicated than that. The plugin API is there to give the users all possible freedom, so with that and events you can basically build whatever you want.
