### ISSUE TITLE
change and changeColor events fire on blur

### ISSUE THREAD

**Issue by iamdriz** [farbelous/bootstrap-colorpicker#222]
If I have an input with the colorpicker attached, the events for both change and changeColor are triggered when the user blurs the input (even though nothing has changed).

e.g.
~~~
$('input')
    .colorpicker()
    .on('change', function(e) { console.log('change'); })
    .on('changeColor', function(e) { console.log('changeColor'); });
~~~
Why is this happening? Surely both of these events should ONLY fire when the actual contents of the input has changed.

**Comment by iamdriz** [comment]
I came up with a fix:
~~~
$('input')
    .attr('data-value', $(this).val())
    .colorpicker()
    .on('change', function() {
        if( $(this).val() !== $(this).attr('data-value') ) {
            console.log('change');
            $(this).attr('data-value', $(this).val());
        }
    });
~~~
So we basically listen for the change event like before but only do anything if the actual colour is different from the previous one.

**Comment by itsjavi** [comment]
Hello thanks for reporting, I would really appreciate if you could open a pull request with your fix :) thanks

**Comment by itsjavi** [comment]
This is fixed now on master https://farbelous.github.io/bootstrap-colorpicker/tutorial-DebugMode.html
