### ISSUE TITLE
Pick only predefined colors

### ISSUE THREAD

**Issue by bardware** [farbelous/bootstrap-colorpicker#226]
The color picker has a `colorSelectors` setting that allows to add named colors to the picker dialog.
I'd like the user to select exclusively one of the predefined colors.
Is there a picker mode that allows only to select from predefined colors?

TinyMCE has this:
![grafik](https://user-images.githubusercontent.com/802702/30282847-bfca60b0-9716-11e7-870d-9d7e4ec2a5c5.png)

**Comment by itsjavi** [comment]
duplicated of https://github.com/farbelous/bootstrap-colorpicker/issues/119

as mentioned there, you can edit the colorpicker template to remove the hue/saturation/alpha bars and leave only the colorSelectors, now named `colorPalette` in v3.
