### ISSUE TITLE
Custom color selectors fail to set color of thumbnail

### ISSUE THREAD

**Issue by Rosebudlia** [farbelous/bootstrap-colorpicker#228]
When setting the color using a custom swatch (i.e. colorSelector thumbnail), the color of the main thumbnail (within span 'input-group-addon') is set to the alias name. This means that the color of this main thumbnail does not update if the alias is not a standard HTML color name such as aquamarine or slategrey.

**Comment by itsjavi** [comment]
thanks for reporting, that's definitely a bug, I saw it in the demos

**Comment by itsjavi** [comment]
This has been fixed in master branch, soon available as v3
