### ISSUE TITLE
Dynamically lighting the color

### ISSUE THREAD

**Issue by yalwayzm33** [farbelous/bootstrap-colorpicker#231]
Hi,

i am trying to dynamically lighten the shade of the third element 

using this code

        .on('changeColor', function(e) {
               var box_id = $(this).attr('box-id');
               var box_class = $(this).attr('box-class');
              var elements = $('#box-container-' + box_id + ' .' + box_class);

               for(var i = 0; i < elements.length -2 ; i++){
                     elements[i].setAttribute('style', 'background-color: ' + e.color + ' !important');
               }
               // this element need to have a light shade but i am not able to achieve it = lightcolor should be 
              light shade of e.color
               elements[2].setAttribute('style', 'background-color: ' + lightcolor+ ' !important');

color picker documentation doesn't help much in this case ..

**Comment by itsjavi** [comment]
Please provide a live example as requested in the CONTRIBUTING.md guidelines and issue template
https://raw.githubusercontent.com/farbelous/bootstrap-colorpicker/master/.github/ISSUE_TEMPLATE.md

Thanks

**Comment by itsjavi** [comment]
Currently this library does not support color calculations out of the box. You can play with the `e.color` object h,s,b,a property values and then call `e.color.toString()`.
