### ISSUE TITLE
#aN when clicking on slider for empty textbox

### ISSUE THREAD

**Issue by DeyaZ88** [farbelous/bootstrap-colorpicker#233]
if the user typed deleted the content of the text-box , then opened the color picker , then clicked on color slider , #aN value will appear inside the text-box.

![screenshot-2017-10-22 colorpicker for twitter bootstrap](https://user-images.githubusercontent.com/536752/31863195-e951211a-b752-11e7-8b7a-3790e004b63e.png)

**Comment by itsjavi** [comment]
fixed on master
