### ISSUE TITLE
colorpicker don't follow item in modal

### ISSUE THREAD

**Issue by Kurairaito** [farbelous/bootstrap-colorpicker#234]
Hi,

When using colorpicker in a scrollable modal view, when the colors picker is shown, if you scroll with the mouse's wheel, the colorpicker don't move

Example (the modal automaticcaly open, click the right rectangle to open color picker and then scroll the page):
http://jsfiddle.net/g4b2bdqp/3/

Expected behavior is, like in a normal page, follow the parent element.

Note : tested with bootstrap 3.3.5 & firefox

Best regards,
Kurairaito

**Comment by itsjavi** [comment]
Ok this needs investigation. I have in mind a major refactoring to revisit the used Bootstrap components and remove all possible tweaks so the original code is used as much as possible. This should make this library consistent with the original BS components.
There is no quick solution for now.

PS: Thanks for providing an example I really appreciate that.

**Comment by Herst** [comment]
You can use `container: true` but then the alignment will be off: http://jsfiddle.net/gt0x7u4j/
