### ISSUE TITLE
[Question] How to get the value from inside event

### ISSUE THREAD

**Issue by seblavoie** [farbelous/bootstrap-colorpicker#235]
This might be a beginner question, but I couldn't wrap my head around a way to do this. 

I am trying to get the color from the function fired on the `hidePicker` event. I've tried a couple of things and looked around in the documentation, but really can't find a way. Here's the code:

```
$(".js-colorpicker").colorpicker({
  component: ".input-group-addon"
}).on({
  hidePicker: function(e){
    // How can I get the color value from here?
  }
});
```

If you can help me out with this, I could me make a pull request adding to the documentation what I was initially missing. Thanks :)

**Comment by tharangachaminda** [comment]
`$(".js-colorpicker").colorpicker({
  component: ".input-group-addon"
}).on('hidePicker', function(e){
    var yourColor = $(this).val();
    // further more, you can access e.color object to do various things like color mode conversion etc...
  });`

**Comment by itsjavi** [comment]
Actually it is in the documentation source code, section "working with events"
https://farbelous.github.io/bootstrap-colorpicker/

```js
<a href="#" class="btn btn-default" id="cp4">Change background color</a>
<script>
    $(function() {
        $('#cp4').colorpicker().on('changeColor', function(e) {
            $('body')[0].style.backgroundColor = e.color.toString(
                'rgba');
        });
    });
</script>
```
