### ISSUE TITLE
Popup width expands

### ISSUE THREAD

**Issue by moafim** [farbelous/bootstrap-colorpicker#236]
After every click, popup width expands more
<img width="936" alt="screen shot 1396-08-19 at 14 12 06" src="https://user-images.githubusercontent.com/33544852/32655014-2e1919c4-c621-11e7-8342-18acd2376f22.png">
<img width="558" alt="screen shot 1396-08-19 at 14 11 58" src="https://user-images.githubusercontent.com/33544852/32655017-2ef08a1c-c621-11e7-8790-2fec627102ce.png">

**Comment by moafim** [comment]
I'm using Bootstrap4 by the way

**Comment by itsjavi** [comment]
Hello It's mandatory to report bugs using the Issues [template](https://raw.githubusercontent.com/farbelous/bootstrap-colorpicker/master/.github/ISSUE_TEMPLATE.md) (that apparently you cleared).
We can only help if a live example is provided.
Thanks for understanding

**Comment by itsjavi** [comment]
By the way BS4 won't  be supported until the final version + minimum bugfix `v4.0.5` is released.
