### ISSUE TITLE
Swatch not wrapping

### ISSUE THREAD

**Issue by zishani** [farbelous/bootstrap-colorpicker#248]
Hi,

How do I get the swatches palette to wrap around to the width of the picker control? Currently mine is like this:
![image](https://user-images.githubusercontent.com/28621048/35766770-cdad056c-08d5-11e8-91ed-88e8e62b2343.png)

I assume I need to apply a customClass - but then what css property do I need to target of the picker for specifying the width in?

I don't think I want to set container: true as this makes the width of the picker the width of my textBox which is too wide.
 
Thanks

**Comment by itsjavi** [comment]
right, you have to style the swatch box until we fix that css issue

**Comment by itsjavi** [comment]
<img width="209" alt="screen shot 2018-07-22 at 23 25 37" src="https://user-images.githubusercontent.com/122741/43050285-93f052b4-8e06-11e8-8c5f-8291cb4a3b41.png">

This is fixed in version `3.0.0-beta.4`, which comes with better pixel-perfect styling
