### ISSUE TITLE
Error in IE11: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by MedusaDelft** [farbelous/bootstrap-colorpicker#250]
### Description

Error in IE11: Object doesn't support property or method 'assign'. File: bootstrap-colorpicker.min.js (9,7162)

Same code runs fine in Firefox and Chrome. Edge not tested yet.

### Context

- bootstrap-colorpicker version: 3.0.0
- bootstrap version: 4.0.0-dist
- jQuery version: 3.3.1
- Browser name and version: IE11, 11.248.16299.0 (update 11.0.51 KB4074736)
- Operative System name an version: Windows 10

### Expected behavior

Clicking button shows dialog (modal) with a form-entry with the colorpicker.

### Actual behavior

Clicking button does not work (javascript error)

### Live Example

{Please write here a link to your JsFiddle example}

**Comment by itsjavi** [comment]
Hello @MedusaDelft this is due to IE11 not compatible with that EcmaScript version
you may need a ES5 or ES6 shim for that
https://stackoverflow.com/questions/35215360/getting-error-object-doesnt-support-property-or-method-assign

**Comment by MedusaDelft** [comment]
Ok, thank you for the info. I had not realised this.
Getting another error now, so I think I have to look for a different picker unfortunately.

**Comment by itsjavi** [comment]
Ok, you can also try to use a version previous to 3.0 of this plugin, which should be using a less modern javascript

**Comment by Herst** [comment]
> Getting another error now, so I think I have to look for a different picker unfortunately.

I haven't encountered any such issues after applying the `Object.assign` shim.

**Comment by MedusaDelft** [comment]
@Herst I got an error with the  toRgbString function
