### ISSUE TITLE
Not working on IE10, IE11

### ISSUE THREAD

**Issue by doblementa** [farbelous/bootstrap-colorpicker#251]
### Description

The plugin is not working on Internet Explorer. Any solution?

### Context

- bootstrap-colorpicker version: 3
- bootstrap version: 3.3.7
- jQuery version: 3.1.1
- Browser name and version: Internet Explorer
- Operative System name an version: -

**Comment by itsjavi** [comment]
Version 3 will drop support for old browsers and that includes all Internet Explorer browsers. Maybe that should be clarified in the documentation.

Please try version 2 of the plugin or use an IE shim ES6 plugin.

Duplicated of #250

But I will keep this open to remember to update the docs.

**Comment by itsjavi** [comment]
also, which version of IE are you talking about?

**Comment by Herst** [comment]
IE11 is the latest browser for Windows 7 which will be supported until 2020, see https://support.microsoft.com/en-us/help/4057281 and https://support.microsoft.com/help/17454, and still has a desktop browser market usage of nearly 6%, see http://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/

It's also worth noting that Bootstrap 4 supports IE10 and 11.

**Comment by doblementa** [comment]
Hi,

I don't know which version was being testing, it was the client who detected the problem (I, obviously, don't, use IE ;D).

Anyway, thank you very much about all the info.!

**Comment by Herst** [comment]
> I cannot even test because I am not a windows user.

You could use the free virtual machines from Microsoft: <https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/>

But I totally get you, it's an incredible hassle. I am working at a project which should test again with IE soon and I am dreading it.

**Comment by itsjavi** [comment]
Fixed for both IE10 and IE11 in `v3.0.0-beta.3`
