### ISSUE TITLE
Enhancement for transparent input-group-addon background

### ISSUE THREAD

**Issue by BrainFeeder** [farbelous/bootstrap-colorpicker#254]
Adding the following CSS will add the 'transparent' image background to the selected color in the swatch.
Users will then see if an alpha channel is selected on the colorpicker, without having to open it first.

![trans-ext](https://user-images.githubusercontent.com/4141465/37858156-b83c6f22-2f01-11e8-99f5-556f4a11b6ef.PNG)

    .colorpicker-component .input-group-addon em {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAABkCAQAAAAVxWkcAAABr0lEQVR4Xo2VwU0DQQxF7dmRuNIFlzlSAR3QAaXQQdIBJVABFXDcOVAAd67cjJLR07dkhcSrkZKfb/t7bG88rFo3B5gZPMNycItu2xloGV7MWHzM9zuzFWCkmA0nK6AszCUJDW6+mG6R03ncw5v8EMTEvZ2O3AliYjpslblc0RF9LmZYWxURU6aKytWZYsoWCAe+xwOZp1GsEukGiIkYxcQCHck99+gRgB7JncyIB5SGEhP3Yh5P6JwX+u6AnYot104d8DJT7uH7M9JH6OZbimj0vfMVaYnJIZFJDBW9kHlerL2C6JV4mSt7uuo2N57RxnZ+usQjn0R1jwBJBrNO3evJpVYUWsJ/E3UiXRlv24/7YZ04xmEdWlzcKS+B/eapeyMvFd2k0+hRk/T0AmTW8h69s2sjYMsdPntECiILhAeIMZAeH4QvUwfn6ijC0tTV+fT9ky8jM9nK2g7Ly1VjSpKYq6IvsAm7MtNu1orEqa/K3KNvgMFdhfquPfJmp2dbh0/8Gzb6Y22ViaNr6n5410zXdngVhbu6XqdOtWOuin5hjABGp4a2uotZ71MVCfwDBt2/v37yo6AAAAAASUVORK5CYII=);
        background-position: 0 100%;
        height:16px;
    }
    .colorpicker-component .input-group-addon i {
        margin-top:-2px;
    }

In the HTML I simply wrapped the `<i></i>` with `<em></em>`.

(I'm using Bootstrap 4, for other versions adding this styling might be a bit different.)

**Comment by itsjavi** [comment]
thanks I will consider adding this background by default in the add-ons

**Comment by itsjavi** [comment]
added in https://github.com/farbelous/bootstrap-colorpicker/commit/7ccb2001b84712e7c892a27e754af8960802e75a
