### ISSUE TITLE
changeColor Event not working

### ISSUE THREAD

**Issue by Mobashir1995** [farbelous/bootstrap-colorpicker#255]
I'm trying to change the background color of a section with the colorchange event. But The colorchange event not triggering.
 There is also not error showing on my console.
Here is my code
`jQuery('#bar-bg-color').colorpicker().on('changeColor', function(e){
console.log( jQuery(this).colorpicker('getValue', '#a0d4e3') );
 jQuery('.star-timer-bar').css("background-color", jQuery(this).colorpicker('getValue', '#a0d4e3') );
 });`

I'm using jQuery 3.3.1 and bootstrap 4.

**Comment by itsjavi** [comment]
hello what version of the plugin are you using?
