### ISSUE TITLE
Not working with Bootstrap 4

### ISSUE THREAD

**Issue by joshuajott** [farbelous/bootstrap-colorpicker#258]
### Description

When using ONLY bootstrap 4 the control renders the swatch selector oddly.  Bootstrap 4 uses a div "input-group-append" as the wrapper of items in a group with an input.   Tried that but then swatch doesn't even appear.  

### Context

- bootstrap-colorpicker version:  most recent 3.0.0 beta
- bootstrap version:  4
- jQuery version:  3.2.1
- Browser name and version:  Chrome +ALL
- Operative System name an version: Windows, OSX

### Expected behavior

The Swatch selector box should render in Bootstrap 4 as it did in Bootstrap 3 but it is not.

### Actual behavior

Swatch should fill right side in Bootstrap 4 as it properly does in Bootstrap 3.

### Live Example

{Please write here a link to your JsFiddle example}
![swatchissue](https://user-images.githubusercontent.com/13575875/38217488-9804e52a-369c-11e8-80e1-5cc5d378dc10.PNG)

**Comment by itsjavi** [comment]
That's true, It was working with BS 4.0.0 beta2
but seems that final 4.0.0 has breaking changes 😞

**Comment by joshuajott** [comment]
yea they decided to change css/js stuff when it comes to input groups w/ buttons

**Comment by SKTheo** [comment]
This works for me:

```
<div id="id1" class="input-group colorpicker-component formcolorpicker">
    <input type="text" name="name1" id="id2" value="#000" class="form-control"/>
    <div class="input-group-append">
        <span class="input-group-text input-group-addon"><i></i></span>
    </div>
</div>

$('.formcolorpicker').each(function () {
    $(this).colorpicker();
});
```

**Comment by joshuajott** [comment]
@SKTheo Thanks man! Great work around

**Comment by itsjavi** [comment]
Yes, you basically need to change the addon layout. For the rest, it should work fine.
I will update the examples in the docs to use BS4.1
