### ISSUE TITLE
alpha channel not working if initial color has hex format

### ISSUE THREAD

**Issue by itsjavi** [farbelous/bootstrap-colorpicker#259]
### Description

Seems that the alpha channel/bar is not working when working with hex colors.

### Context

Latest docs:
https://farbelous.io/bootstrap-colorpicker/tutorial-Basics.html

### Expected behavior

When changed the alpha setting, the color format should change accordingly if the `useAlpha` setting is not false and the `format` is automatic or a non-opaque format.

### Actual behavior

The alpha setting is ignored, e.g. when the initial color is hex.

### Live Example

https://farbelous.io/bootstrap-colorpicker/tutorial-ColorSwatches.html

**Comment by CrandellWS** [comment]
https://github.com/bgrins/TinyColor/blob/master/tinycolor.js ... perhaps this could be helpful for conversions... idk ... I did not want to open an issue to say that...

**Comment by itsjavi** [comment]
@CrandellWS thanks, this issue was already resolved. The plugin is using another color conversion library https://github.com/Qix-/color
