### ISSUE TITLE
Unable to use prgb format

### ISSUE THREAD

**Issue by ndumngalon** [farbelous/bootstrap-colorpicker#261]
### Description

When using the format prgb the value of my input field because false and unable to select colors

### Context

- bootstrap-colorpicker version: 2.5.2
- bootstrap version: 3.3.7
- jQuery version: 2.2.4
- Browser name and version: Chrome 66.0v
- Operative System name an version: Ubuntu 16.04
### Expected behavior

The color in plain

### Actual behavior

false

### Live Example

{Please write here a link to your JsFiddle example}

**Comment by itsjavi** [comment]
prgb? what format is that?

Please provide an example of the code you are using in JSFiddle.
