### ISSUE TITLE
I have doubt, help please. 

### ISSUE THREAD

**Issue by 123survesh** [farbelous/bootstrap-colorpicker#262]
Hi, 
I am new to using javascript components that are created with jquery. I have used components that were created using simple javascript before.

I have doubt here. How do I access the 'colorpicker' Object's attributes and methods? 
Usually I create an object like this:
    var a = new Object_name({arguments});
So I use the object "a" to perform all the necessary functions, using the '.' operator
But here we are creating the object like this $('#target').colorpicker({arguments});
How do I perform the necessary operations now?

**Comment by itsjavi** [comment]
Hi, you have all your answers in the documentation and its source code https://farbelous.io/bootstrap-colorpicker/v2/
`.data('colorpicker')`

Please next time read the documentation before opening an issue like this.

**Comment by 123survesh** [comment]
Sorry @itsjavi  Noob here. I skipped that link as it said it was a older documentation. I was searching in the newer docs :sweat_smile: 
Thanks for the reply :+1:
