### ISSUE TITLE
[feature request] [helpwanted] Move input field in settings window

### ISSUE THREAD

**Issue by ElodieBergonnier** [farbelous/bootstrap-colorpicker#263]
### Description
Hello,

I would like to use your colorpicker to set multiple colors (a color palettes actually). So I tried to build a condensed mode where the input field (used to display and set the color value) is not directly visible. I would like to move this input field into the color settings element but did not find how to do this. See screenshots  below for of actual and wanted behavior.

### Actual behavior
![actual_behavior](https://user-images.githubusercontent.com/12999895/39618220-1113d4a4-4f83-11e8-8a88-5c95fb56f396.png)

### Wanted behavior
![wanted_behavior](https://user-images.githubusercontent.com/12999895/39618157-b5923b16-4f82-11e8-96d0-df9585967f32.png)

**Comment by itsjavi** [comment]
Hi @ElodieBergonnier you can accomplish this using a custom template (check the plugin options in the docs) and events.

**Comment by ElodieBergonnier** [comment]
Thank you for your help and your quick answer. I struggled a bit with focussing into the input text but I managed to reach my goal!

Here is the jsfiddle this the solution : 
http://jsfiddle.net/ElodieBergonnier/b6gjjcay/11/

**Comment by itsjavi** [comment]
That's great! =) thank you for sharing your live example
