### ISSUE TITLE
Custom size no work

### ISSUE THREAD

**Issue by MickaKymm** [farbelous/bootstrap-colorpicker#264]
Custom size works but the picker no longer works like your example => https://farbelous.io/bootstrap-colorpicker/tutorial-CustomSize.html

**Comment by deadkat666** [comment]
yep, same here, i'm not using inline mode and the colorpicker always set the color to be #000000 .
![capture d ecran 65](https://user-images.githubusercontent.com/9334176/41152547-352a1ad6-6b14-11e8-8647-2af6aff0a481.png)
