### ISSUE TITLE
Color picker always returning #000000

### ISSUE THREAD

**Issue by cheborneck** [farbelous/bootstrap-colorpicker#265]
### Description

{No matter what color I pick from a slider or the swatch, the value returned is always #000000
`			$('.bootstrap-colorpicker').colorpicker({
				customClass: 'colorpicker-2x',
				useAlpha: false,
				format: 'hex/hex6',
				horizontal: false,
				sliders: {
					saturation: {
						maxLeft: 200,
						maxTop: 200
					},
					hue: {
						maxTop: 200
					},
					alpha: {
						maxTop: 200
					}
				},
				debug: true
			});
`
I tried the previous version which worked but didn't want the alpha slider which I guess you couldn't hide (hex only colors wanted).

COMMENT update: I was looking through your master branch announcement and noticed you switched over to use popper. I have found that popper is 
}

### Context

- bootstrap-colorpicker version: {3.0.0-beta.1}
- bootstrap version: {4.0.0}
- jQuery version: {3.1.1}
- Browser name and version: {ANY}
- Operative System name an version: {windows 10}

### Expected behavior

{Please write here}

### Actual behavior

{Please write here}

### Live Example

{Please write here a link to your JsFiddle example}

**Comment by itsjavi** [comment]
Hi, without a live example I cannot debug this properly. I see that you omited that part.
Also, `hex/hex6` is not a supported format string.

**Comment by SanderVanKeer** [comment]
I have the same issue. If I post a field that uses the color picker the $_POST value is always "#000" for some reason. Any ideas?

**Comment by ralison** [comment]
I believe I am having the same issue here. 
In my case it appears to only be when the slider option is provided on initialisation. 

I believe the same behavior is occurring on the example demo at ...
https://farbelous.io/bootstrap-colorpicker/tutorial-CustomSize.html
Note the color is not changing from the initial value

**Comment by chamnap** [comment]
Same here...

**Comment by SanderVanKeer** [comment]
I think I've found a solution. At first I did something like : 
`$('.color-picker').colorpicker();` to initiate the colorpicker component on all elements with the class 'color-picker'. 

I found out you actually need to do something like this:
`	$('.color-picker').each(function() {
		$(this).parent().colorpicker();
	});`

**Comment by itsjavi** [comment]
I definitely want to investigate this. I hope I have time this week
