### ISSUE TITLE
Can RGB and hexadecimal input color values be integrated into the plug-in's colorpicker panel

### ISSUE THREAD

**Issue by kaivin** [farbelous/bootstrap-colorpicker#266]
### Description

I want to get the color in the plug-in colorpicker panel by entering the color value, because in some scenarios the text input box is not displayed

### Context

- bootstrap-colorpicker version: {2.5.2}
- bootstrap version: {bootstrap4.0.0}
- jQuery version: {jquery3.3.1}
- Browser name and version: {Please write here}
- Operative System name an version: {Please write here}

### Expected behavior

{Please write here}

### Actual behavior

{Please write here}

### Live Example

{Please write here a link to your JsFiddle example}

**Comment by itsjavi** [comment]
you can accomplish that using the events and the custom template option if needed
