### ISSUE TITLE
v2.5.3 breaking changes

### ISSUE THREAD

**Issue by leptest** [farbelous/bootstrap-colorpicker#271]
The removal of IE >= 10 supports seems like a breaking change.

Shouldn't this get a semantic major bump?

**Comment by itsjavi** [comment]
Hi, there are any plans to remove IE10+ support for Bootstrap Colorpicker v2.x or v3.x,
but it is true that there are not on top of my priorities right now.

If you find any problem with them, please report an issue.

Thanks :)

**Comment by leptest** [comment]
Ah yes you are correct!  Sorry 😄 

And i also read [this line](https://github.com/farbelous/bootstrap-colorpicker/compare/d56d0d3d5bee59904d48bce3c47a0029741e10e6...525cd6a0aa26ae95803bbf34d231c4163136a314#diff-8cc7b2b0d78dd2501610391c086a8516L39) wrong, it was for contributing, not browser support.

Thanks for your help!

**Comment by itsjavi** [comment]
Yes no prob., it just says "test at least on these browsers..."
I removed IE to facilitate testing to all the contributors.
