### ISSUE TITLE
DevTools failed to parse SourceMap 

### ISSUE THREAD

**Issue by poradz** [farbelous/bootstrap-colorpicker#274]
DevTools failed to parse SourceMap
![image](https://user-images.githubusercontent.com/31520119/44913423-a3521800-ad2d-11e8-9c5f-543a8fd7562a.png)

Maybe it is connected with #272, but I'm not sure.

**Comment by amatyi96** [comment]
@itsjavi I think you should delete the comment from the beginning of the file (bootstrap-colorpicker.min.js.map, bootstrap-colorpicker.js.map), because it is not possible to use comment in JSON file and it will work!
