### ISSUE TITLE
Is it possibile to use only 'spectrum' to pick color?

### ISSUE THREAD

**Issue by fabiocaccamo** [farbelous/bootstrap-colorpicker#275]
![schermata 2018-09-04 alle 12 49 27](https://user-images.githubusercontent.com/1035294/45027682-61cdaf80-b042-11e8-9a39-2e3ad65e1184.png)

**Comment by itsjavi** [comment]
I think it is possible to do that, you can costumize the colorpicker almost however you want
you will need to adjust the backgrounds, css, and JS config for the sliders
