### ISSUE TITLE
Initialize by class selector

### ISSUE THREAD

**Issue by harmonmi** [farbelous/bootstrap-colorpicker#278]
Is there a way to initialize multiple colorpickers at once by class selector? I tried a few options, such as initializing colorpicker on a single class selector, as well as looping through each element with a class and initializing that element. No luck so far.

**Comment by itsjavi** [comment]
please provide an example like it was described in the issue template

**Comment by ken-muturi** [comment]
`
    //html
    <span class="letter" data-letter="A">A</span>
    <span class="letter" data-letter="B">B</span>
    <span class="letter" data-letter="C">C</span>
    <span class="letter" data-letter="D">D</span>
    <span class="letter" data-letter="E">E</span>
    <span class="letter" data-letter="F">F</span>

    // js    

    $('span.letter').colorpicker().on('changeColor', function(event) {
    $('span.letter').css('color', event.color.toString());
    });`
`
`
