### ISSUE TITLE
Firefox: mouse-dragging in color-selection-popup selects text behind

### ISSUE THREAD

**Issue by Fennes3** [farbelous/bootstrap-colorpicker#283]
### Description

In firefox there occours a random selection of text of the page behind color-selection-popup while mouse-dragging in the popup. This also happens on the example-page (https://farbelous.io/bootstrap-colorpicker/tutorial-Basics.html)

### Context

- bootstrap-colorpicker version: v3.0.3
- bootstrap version: v4.1.1
- jQuery version: {Please write here}
- Browser name and version: Firefox 62.0.2 (64-Bit)
- Operative System name an version: Windows 10

### Expected behavior

No selection of text of the page behind the popup while mouse-dragging

### Actual behavior

Selection of text of the page behind the popup while mouse-dragging

### Live Example

https://farbelous.io/bootstrap-colorpicker/tutorial-Basics.html

**Comment by Fennes3** [comment]
Following piece of css fixes this behaviour for Firefox:
```
.colorpicker.colorpicker-popup {
    -moz-user-select: none;
}
```

**Comment by MrMaavin** [comment]
The issue still exists, but it works greate with the css fix of @Fennes3 :

> Following piece of css fixes this behaviour for Firefox:
> 
> ```
> .colorpicker.colorpicker-popup {
>     -moz-user-select: none;
> }
> ```
