### ISSUE TITLE
Increase size of colorpicker

### ISSUE THREAD

**Issue by adityacoder007** [farbelous/bootstrap-colorpicker#287]
This does increase the width and height but unable to select colors in bottom right quarter. And can't drag pointer beyond the top half as well. Any workaround?

_Originally posted by @adityacoder007 in https://github.com/farbelous/bootstrap-colorpicker/issue_comments#issuecomment-439488866_

**Comment by itsjavi** [comment]
please take a look at the working example https://farbelous.io/bootstrap-colorpicker/tutorial-p02_Advanced_Examples.html

and please do not remove issue templates next time otherwise the issue will be closed.
