### ISSUE TITLE
Synchronizing multiple colorpickers

### ISSUE THREAD

**Issue by RouNNdeL** [farbelous/bootstrap-colorpicker#289]
I'm trying to synchronize the values across multiple colorpickers when the user checks a checkbox. Right now every method that updates the colorpicker triggers the `onchange` event thus causing a `RangeError: Maximum call stack size exceeded`. Is there any way to update the visuals of the picker without an event firing?

**Comment by itsjavi** [comment]
did you try using event.stopPropagating()?

**Comment by RouNNdeL** [comment]
I was using 3.0.0-beta at the time. Since then the new `change` event isn't triggered when using `setValue` (`colorpickerChange` is). So I manged to achieve the effects without `event.stopPropagating()`. For anyone that comes across (any improvements to this code are welcome): 
```javascript
$(COLORPICKER_SELECTOR).on('change', function(e) {
    if(update_all) {
        $(COLORPICKER_SELECTOR).not($(this)).colorpicker("setValue", e.value);
    }
}).colorpicker(COLORPICKER_OPTIONS);
```

**Comment by itsjavi** [comment]
yes I remember now it was fixed, sorry for the late response

**Comment by RouNNdeL** [comment]
Thanks for the response by the way. Gave it another go, to double check that `event.stopPropagating()` solution, and I have it working thanks to that :)
