### ISSUE TITLE
laravel 5.8 function not found

### ISSUE THREAD

**Issue by alighasemzadeh** [farbelous/bootstrap-colorpicker#293]
Hello,
I am using laravel 5.8 (https://github.com/pcshiraz/ecommerce) and I want to use boostrap colorpicker.

I add `window.colorPicker = require('bootstrap-colorpicker');` to app.js and call a function `$('.color').colorpicker();` but I get `16:314 Uncaught TypeError: $(...).colorPicker is not a function` and it doesn't work.

**Comment by itsjavi** [comment]
I am not sure how you integrate the plugin or what version are you using, but for what you say you are assigning it to the window object instead of the jQuery object.

Closing, because it's not a bug.

**Comment by alighasemzadeh** [comment]
@itsjavi 
I see only color poppers.Check image:
![2019-04-03](https://user-images.githubusercontent.com/26847446/55463804-07fc8a80-560f-11e9-872e-f65cd54a08b8.png)
