### ISSUE TITLE
Change Dimensions of the picker

### ISSUE THREAD

**Issue by alithestar2000** [farbelous/bootstrap-colorpicker#296]
How can i resize the picker?

### Description

{Please write here}

### Context

- bootstrap-colorpicker version: {Please write here}
- bootstrap version: {Please write here}
- jQuery version: {Please write here}
- Browser name and version: {Please write here}
- Operative System name an version: {Please write here}

### Expected behavior

{Please write here}

### Actual behavior

{Please write here}

### Live Example

{Please write here a link to your JsFiddle example}

**Comment by itsjavi** [comment]
please read the documentation before creating new issues

https://farbelous.io/bootstrap-colorpicker/tutorial-p02_Advanced_Examples.html
